name: Publish

# curl -H "Authorization: token <github-token>" -H 'Accept: application/vnd.github.everest-preview+json'  "https://api.github.com/repos/<organization>/<repository>/dispatches" -d '{"event_type": "publish", "client_payload": {"releaseVersion": "<release-version>", "postReleaseVersion": "<post-release-version>", "username": "<username>", "email": "<email>"}}'

on:
  repository_dispatch:
    types: [publish]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1.3.0
      with:
        java-version: 8
    - name: Set Release Version
      run: sed -ir 's/^\([[:space:]]*version[[:space:]]*=[[:space:]]*\(['"'"'"]\)\)[^'"'"'"]*\2/\1${{ github.event.client_payload.releaseVersion }}\2/g' build.gradle
    - name: Build
      run: ./gradlew build --write-locks --info --stacktrace --warning-mode=fail
    - name: Publish
      run: ./gradlew publishPlugins --info --stacktrace --warning-mode=fail
    - name: Release
      run: |
        git config user.name '${{ github.event.client_payload.username }}'
        git config user.email '${{ github.event.client_payload.email }}'
        git add build.gradle gradle/dependency-locks
        git commit -m 'v${{ github.event.client_payload.releaseVersion }}'
        git tag -a 'v${{ github.event.client_payload.releaseVersion }}' -m 'v${{ github.event.client_payload.releaseVersion }}'
        sed -ir 's/^\([[:space:]]*version[[:space:]]*=[[:space:]]*\(['"'"'"]\)\)[^'"'"'"]*\2/\1${{ github.event.client_payload.postReleaseVersion }}\2/g' build.gradle
        rm -rf gradle/dependency-locks
        git add build.gradle gradle/dependency-locks
        git commit -m 'Update version after release'
        git push --follow-tags origin HEAD:$GITHUB_REF
