name: Pull Request

on: pull_request

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        jdk: [8, 11]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1.3.0
      with:
        java-version: ${{ matrix.jdk }}
    - name: Build
      run: ./gradlew build "-PgradleVersions=6.1.1,current" --info --stacktrace --warning-mode=fail
